### ISSUE TITLE
What is the SRN private key?

### ISSUE THREAD

**Issue by Sateetje** [proximax-storage/sirius-storage-mainnet-onboarding#4]
What is the SRN private key?

Where does it needs to be generated? Or can the SDNs private key be used?

![afbeelding](https://user-images.githubusercontent.com/16215404/99969706-23477b00-2d9b-11eb-96bf-1302ccdb2668.png)

**Comment by shinneng** [comment]
https://storagedocs.xpxsirius.io/docs/getting_started/economy/
SRN private key requires `prx.xpx` and/or `prx.so` to deposit to Drive.
