### ISSUE TITLE
SDN: generate_address

### ISSUE THREAD

**Issue by Sateetje** [proximax-storage/sirius-storage-mainnet-onboarding#5]
The explanation of installing SDN starts with generate_address, this tool isn't in the director directory but in the tools directory. Change description so people can copy/paste and/or know where to find the tool.

BTW: the tool hasn't execute rights by default

![afbeelding](https://user-images.githubusercontent.com/16215404/99969962-76213280-2d9b-11eb-947f-bfa3ab685ca3.png)
![afbeelding](https://user-images.githubusercontent.com/16215404/99970078-a4067700-2d9b-11eb-8e03-a7500cb8180d.png)

**Comment by shinneng** [comment]
as highlighted in the README,  it is recommended that the user generates a SDN or SRN account using a wallet because if the user loses the private key then he/she will lose his/her fund.
