### ISSUE TITLE
What is sufficient balance?

### ISSUE THREAD

**Issue by Sateetje** [proximax-storage/sirius-storage-mainnet-onboarding#6]
What amount of xpx is sufficient balance?

Diskspace isn't involved? What means 1 month / 172800?

![afbeelding](https://user-images.githubusercontent.com/16215404/99970164-c26c7280-2d9b-11eb-95d6-0ade65546747.png)

**Comment by shinneng** [comment]
https://github.com/proximax-storage/sirius-storage-mainnet-onboarding/blame/main/director/README.md#L75
will update `172800` to `172800 blocks` (30days x 5760 blocks per day) 

https://storagedocs.xpxsirius.io/docs/cli/dfms/contract/#examples
Diskspace is mentioned when creating drive `"space": 100` where 100 refers to 100MB

**Comment by Sateetje** [comment]
Clear
