### ISSUE TITLE
Expose private key in bash script(s)

### ISSUE THREAD

**Issue by Sateetje** [proximax-storage/sirius-storage-mainnet-onboarding#7]
The private key of the account generated for the SDN need to be stored in a safe place as well? It's holding xpx (or other mosaics like SO).

Can we use delegated keys or multisig accounts?

Do I really need to put a private key in the bash script and send balance to it?

**Comment by shinneng** [comment]
i don't think it's possible to delegate as the private key is required to manage the node including buy offers and sell offer transaction on the blockchain.

the private key is stored as a `keystore`.  I think it's possible to have a golang utility to generate this `keystore` folder during the initialization.

@alvin-reyes @Wondertan @xgreenx what you guys think?
